UPDATE frameworks_v2 SET logo_img='smartface.png' WHERE framework='Smartface';
UPDATE frameworks_v2 SET logo_img='notfound.png' WHERE framework='AppConKit';
UPDATE frameworks_v2 SET logo_img='apacheflex.png' WHERE framework='Apache Flex';
UPDATE frameworks_v2 SET logo_img='agate.png' WHERE framework='Agate';
UPDATE frameworks_v2 SET logo_img='appceleratortitanium.png' WHERE framework='Appcelerator Titanium';
UPDATE frameworks_v2 SET logo_img='appgyversteroids.png' WHERE framework='AppGyver Steroids';
UPDATE frameworks_v2 SET logo_img='applicationcraft.png' WHERE framework='Application Craft';
UPDATE frameworks_v2 SET logo_img='chocolatechipui.png' WHERE framework='ChocolateChip-UI';
UPDATE frameworks_v2 SET logo_img='corona.png' WHERE framework='Corona';
UPDATE frameworks_v2 SET logo_img='dhtmlxtouch.png' WHERE framework='DHTMLX Touch';
UPDATE frameworks_v2 SET logo_img='dojomobile.png' WHERE framework='Dojo Mobile';
UPDATE frameworks_v2 SET logo_img='emobc.png' WHERE framework='eMobc';
UPDATE frameworks_v2 SET logo_img='framework7.png' WHERE framework='Framework7';
UPDATE frameworks_v2 SET logo_img='gideros.png' WHERE framework='Gideros';
UPDATE frameworks_v2 SET logo_img='handhelddesigner.png' WHERE framework='Handheld Designer';
UPDATE frameworks_v2 SET logo_img='ionic.png' WHERE framework='ionic';
UPDATE frameworks_v2 SET logo_img='iui.png' WHERE framework='iUI';
UPDATE frameworks_v2 SET logo_img='jqtouch.png' WHERE framework='JQ Touch';
UPDATE frameworks_v2 SET logo_img='jquerymobile.png' WHERE framework='jQuery Mobile';
UPDATE frameworks_v2 SET logo_img='kendoui.png' WHERE framework='Kendo UI';
UPDATE frameworks_v2 SET logo_img='kivy.png' WHERE framework='Kivy';
UPDATE frameworks_v2 SET logo_img='marmalade.png' WHERE framework='Marmalade';
UPDATE frameworks_v2 SET logo_img='moai.png' WHERE framework='Moai';
UPDATE frameworks_v2 SET logo_img='mobifyjs.png' WHERE framework='MobifyJS';
UPDATE frameworks_v2 SET logo_img='monocross.png' WHERE framework='Monocross';
UPDATE frameworks_v2 SET logo_img='notfound.png' WHERE framework='Mono for Android';
UPDATE frameworks_v2 SET logo_img='monotouch.png' WHERE framework='MonoTouch';
UPDATE frameworks_v2 SET logo_img='themproject.png' WHERE framework='The-M-Project';
UPDATE frameworks_v2 SET logo_img='neomad.png' WHERE framework='NeoMAD';
UPDATE frameworks_v2 SET logo_img='nimblekit.png' WHERE framework='NimbleKit';
UPDATE frameworks_v2 SET logo_img='nsbappstudio.png' WHERE framework='NSB/AppStudio';
UPDATE frameworks_v2 SET logo_img='onsenui.png' WHERE framework='Onsen UI';
UPDATE frameworks_v2 SET logo_img='phonegap.png' WHERE framework='PhoneGap';
UPDATE frameworks_v2 SET logo_img='qooxdoo.png' WHERE framework='qooxdoo';
UPDATE frameworks_v2 SET logo_img='rarewire.png' WHERE framework='RareWire';
UPDATE frameworks_v2 SET logo_img='rhodes.png' WHERE framework='Rhodes';
UPDATE frameworks_v2 SET logo_img='senchatouch.png' WHERE framework='Sencha Touch';
UPDATE frameworks_v2 SET logo_img='shiva3d.png' WHERE framework='ShiVa 3D';
UPDATE frameworks_v2 SET logo_img='triggerio.png' WHERE framework='Trigger.io';
UPDATE frameworks_v2 SET logo_img='viziapps.png' WHERE framework='ViziApps';
UPDATE frameworks_v2 SET logo_img='vplay.png' WHERE framework='V-Play';
UPDATE frameworks_v2 SET logo_img='wink.png' WHERE framework='wink';
UPDATE frameworks_v2 SET logo_img='xamarin.png' WHERE framework='Xamarin';
UPDATE frameworks_v2 SET logo_img='zeptojs.png' WHERE framework='Zepto.js';
UPDATE frameworks_v2 SET logo_img='nativescript.png' WHERE framework='Nativescript';
UPDATE frameworks_v2 SET logo_img='reactnative.png' WHERE framework='React Native';
UPDATE frameworks_v2 SET logo_img='fusetools.png' WHERE framework='Fusetools';
UPDATE frameworks_v2 SET logo_img='tabrisjs.png' WHERE framework='TabrisJS';
UPDATE frameworks_v2 SET logo_img='unity3d.png' WHERE framework='Unity';
UPDATE frameworks_v2 SET logo_img='codenameone.png' WHERE framework='Codename One';
UPDATE frameworks_v2 SET logo_img='mobilesmith.png' WHERE framework='MobileSmith';
UPDATE frameworks_v2 SET logo_img='enyojs.png' WHERE framework='EnyoJS';
UPDATE frameworks_v2 SET logo_img='qt.png' WHERE framework='Qt';
UPDATE frameworks_v2 SET logo_img='livecode.png' WHERE framework='LiveCode';
UPDATE frameworks_v2 SET logo_img='adobeair.png' WHERE framework='Adobe AIR';
